Set the Tailwind config's preflight CSS to false
This resolves the problem:
Error: ENOENT: no such file or directory, open '/var/task/node_modules/tailwindcss/lib/css/preflight.css'

Also we will grab everything that comes after the first instance of .generated, so this will include things like hover, after, etc. as well.

See https://stackoverflow.com/a/78399488/1134080